apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pr-20210304-4
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: docker-build-and-deploy
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: docker-pvc-workspace