kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-pvc-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sto-ocp-nfs-qtree
  volumeMode: Filesystem